version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
    environment:
      JVM_OPTS: -Xmx3200m

jobs:
  build:
    executor: android-executor
    steps:
      - checkout

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Build APK
          command: ./gradlew clean assembleRelease

      - run:
          name: Install Bundler
          command: gem install bundler

      - run:
          name: Install Fastlane
          command: bundle install

      - run:
          name: Deploy to Firebase
          command: bundle exec fastlane deploy_to_firebase

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
