name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Download Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip -O commandlinetools.zip
        sudo mkdir -p /usr/local/android-sdk
        sudo unzip -q commandlinetools.zip -d /usr/local/android-sdk
        sudo rm commandlinetools.zip
        echo 'export ANDROID_SDK_ROOT=/usr/local/android-sdk' >> $GITHUB_ENV
        echo 'export PATH=$PATH:/usr/local/android-sdk/cmdline-tools/bin' >> $GITHUB_ENV
        echo 'export PATH=$PATH:/usr/local/android-sdk/platform-tools' >> $GITHUB_ENV
        yes | /usr/local/android-sdk/cmdline-tools/bin/sdkmanager --licenses
        /usr/local/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Build with Gradle
      run: ./gradlew clean assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk